export const techData = {
  Web: [
    { name: 'React', abbr: 'Re' },
    { name: 'Next.js', abbr: 'Nx' },
    { name: 'TypeScript', abbr: 'TS' },
    { name: 'Node.js', abbr: 'No' },
    { name: 'Express', abbr: 'Ex' },
    { name: 'MongoDB', abbr: 'Mg' },
    { name: 'PostgreSQL', abbr: 'Pg' },
    { name: 'Redis', abbr: 'Rd' },
    { name: 'Kubernetes', abbr: 'Kb' },
    { name: 'Docker', abbr: 'Dk' },
    { name: 'Vercel', abbr: 'Vc' },
    { name: 'Tailwind', abbr: 'Tw' },
  ],
  Mobile: [
    { name: 'Flutter', abbr: 'Fl' },
    { name: 'React Native', abbr: 'RN' },
    { name: 'Swift', abbr: 'Sw' },
    { name: 'Kotlin', abbr: 'Kt' },
    { name: 'Firebase', abbr: 'Fb' },
    { name: 'Supabase', abbr: 'Sb' },
    { name: 'GraphQL', abbr: 'Gq' },
    { name: 'REST APIs', abbr: 'Rs' },
  ],
  'AI & ML': [
    { name: 'Python', abbr: 'Py' },
    { name: 'TensorFlow', abbr: 'TF' },
    { name: 'PyTorch', abbr: 'PT' },
    { name: 'n8n', abbr: 'n8n' },
    { name: 'LangChain', abbr: 'LC' },
    { name: 'HuggingFace', abbr: 'HF' },
    { name: 'FastAPI', abbr: 'FA' },
    { name: 'crewAi', abbr: 'CI' },
    { name: 'SQL', abbr: 'SQL' },
    { name: 'scikit-learn', abbr: 'SL' },
  ],
};